-- MySQL Script generated by MySQL Workbench
-- Sun May 18 15:37:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema csr
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `blockchain` ;

-- -----------------------------------------------------
-- Schema csr
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `blockchain` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `blockchain` ;

-- Drop existing tables if they exist
DROP TABLE IF EXISTS `transactions`;
DROP TABLE IF EXISTS `blocks`;

CREATE TABLE blocks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    block_hash VARCHAR(64) NOT NULL UNIQUE,
    block_number BIGINT NOT NULL,
    parent_hash VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    size BIGINT NOT NULL,
    nonce VARCHAR(18) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tx_hash VARCHAR(64) NULL UNIQUE,
    block_id BIGINT NULL,
    block_number BIGINT NULL,
    from_address VARCHAR(42) NOT NULL,
    to_address VARCHAR(42),
    endorser VARCHAR(42),
    uuid VARCHAR(36) NOT NULL UNIQUE,
    input_data TEXT,
    status VARCHAR(7) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (block_id) REFERENCES blocks(id)
);

CREATE INDEX idx_blocks_number ON blocks(block_number);
CREATE INDEX idx_blocks_timestamp ON blocks(timestamp);
CREATE INDEX idx_blocks_hash ON blocks(block_hash);
CREATE INDEX idx_transactions_block_number ON transactions(block_number);
CREATE INDEX idx_transactions_from_address ON transactions(from_address);
CREATE INDEX idx_transactions_to_address ON transactions(to_address);
CREATE INDEX idx_transactions_hash ON transactions(tx_hash);
CREATE INDEX idx_transactions_uuid ON transactions(uuid);